### ISSUE TITLE
请问下定时触发这块能设置个随机时间吗？

### ISSUE THREAD

**Issue by wy1ng** [StoneForests/wpsqiandao#1]
看您的教程上是每天12点整执行，能不能设置成比如12点至13点之间的随机时间执行一次？因为万一每天都是固定时间执行，官方后台判定是用技术手段，可能会导致封号。谢谢！

**Comment by Wenmoux** [comment]
自己改数字就好了

**Comment by wy1ng** [comment]
> 自己改数字就好了

cron表达式的规则我看过了，难道是我理解有问题？都是固定时间啊，求指教怎么改成随机？

**Comment by StoneForests** [comment]
> 看您的教程上是每天12点整执行，能不能设置成比如12点至13点之间的随机时间执行一次？因为万一每天都是固定时间执行，官方后台判定是用技术手段，可能会导致封号。谢谢！

这个我还真不知道。。不过我运行了很久也没发现被封号。。

另外这个之所以每天有11天就是因为在代码中写死了10个固定好友的id，除非你把这10个id也改了，不然官方也很容易发现你在作弊😂。。

**Comment by Wenmoux** [comment]
嗯...我看错了 只能自己设置个时间 至于邀请id你也可以换成别的 别用我写在里边的那几个
